name: '${name}'
version: '${version}'
main: '${main}'
description: 'RSPlugin - ${name}'
api-version: '${api_version}'
depend: [ RSFramework, WorldGuard ]
softdepend: [ ItemsAdder, Oraxen, Nexo ]
authors: [ '${author}' ]