test:
  tick: 20
  block:
    default: "minecraft:barrier"
    replace:
      - "minecraft:stone:10"
      - "minecraft:sand:10"
      - "minecraft:moss_block:10"
      - "minecraft:grass_block:10"
      - "minecraft:mud:10"